### ISSUE TITLE
ReferenceError: PIXI is not defined

### ISSUE THREAD

**Issue by d3dc** [pixijs/pixi-projection#47]
Is it possible to use this plugin without importing all of the core `pixi.js` package?

Naively, could it just check for the existence of the global before assigning?

**Comment by ivanpopelyshev** [comment]
Nope, its using `tsc` without any babels/rollups/webpacks. We are currently working on modules approach but so far its not possible to use `pixi-projection`, `pixi-spine`, `pixi-layers`, and some other plugins cant work without global `PIXI`.

We cant move entirely to ES6 modules because of our typescript plugins legacy and because many really big projects use vanilla PixiJS and people will be very disappointed if we turn it off.

I advice to use PixiJS and all of its plugins as external dependencies. Unless you are making a playable ad. 

Even then, you can put all pixiJS deps in one file and import it across your repository.

**Comment by d3dc** [comment]
That makes sense. Definitely a little awkward when you split your plugin dependencies across a mono-repo. My rollup bundles seem to get the imports right - I'll (re)open an issue if there's some gotchas end-to-end.

**Comment by d3dc** [comment]
I'm still struggling to get the pixi.js side-effects to run. I removed any named imports to prevent tree-shaking. My bundle ends up looking like:
```js
import * as PIXI from 'pixi.js';
import 'pixi-projection';
import _slicedToArray from '@babel/runtime/helpers/esm/slicedToArray';
import _objectWithoutProperties from '@babel/runtime/helpers/esm/objectWithoutProperties'
...
```

**Comment by stefor22** [comment]
@d3dc try add "<script type="text/javascript" src="https://d157l7jdn8e5sf.cloudfront.net/dev/pixi-legacy.js"></script>" in your index.html, it declare a global variable PIXI.

**Comment by ivanpopelyshev** [comment]
Oh right, I forgot to say - you need dev version of pixijs, we dont have it on npm.

**Comment by d3dc** [comment]
@ivanpopelyshev The normal release of PIXI from the CDN seems to work with the projection plugin:
```
https://cdnjs.cloudflare.com/ajax/libs/pixi.js/5.0.4/pixi.min.js
```

I'm still confused as to why the recommended import isn't working.

One thing I noticed, is that there's no `sideEffects` field in the pixi.js `package.json`. That might explain why using webpack doesn't work, but I guess I can't find the relevant file to see why loading the ESM doesn't like it.

**Comment by ivanpopelyshev** [comment]
There's no `BatchShaderGenerator` in the file you referenced. PR with that feature was approved after 5.0.4 was released, its only in `dev` branch.

**Comment by RodrigoHamuy** [comment]
@ivanpopelyshev, how would you recommend me to get this to work with Webpack and Typescript?

https://codesandbox.io/s/pixi-projection-ts-trgm2

**Comment by ivanpopelyshev** [comment]
https://codesandbox.io/s/pixi-projection-7xtqo

**Comment by RodrigoHamuy** [comment]
Thanks @ivanpopelyshev , in the link you send me, I get a `PIXI is not defined` error still in the preview. Is it working for you?

**Comment by ivanpopelyshev** [comment]
oops.
https://codesandbox.io/s/pixi-projection-cmulu

**Comment by ivanpopelyshev** [comment]
```
import * as PIXI from "pixi.js";
global.PIXI = PIXI;
require("pixi-projection");

const app = new PIXI.Application({ width: 256, height: 256 });
const sprite = new PIXI.projection.Sprite2d(
  PIXI.Texture.from("https://i.imgur.com/IaUrttj.png")
);
app.stage.addChild(sprite);
document.body.appendChild(app.view);

```

**Comment by RodrigoHamuy** [comment]
@ivanpopelyshev this works :tada: , thank you!

**Comment by ivanpopelyshev** [comment]
Added it to README. Thanks for the link to sandbox with angular, I dont actually have time to set up those kind of projects :)

**Comment by jjhesk** [comment]
how to fix the error? it seems a big mess in the code.

**Comment by kulabros** [comment]
Hi there, having similar issue, when I tried to migrate my project and all plugins from pixi v4 to v5, all newest release versions.. Before, I used module, including all pixi related imports, exporting pixi on window, which I import in other modules as PIXI, and it worked.
v4 version, ./vendor/pixi.js:

`import "pixi.js";
import "pixi-animate";
import "pixi-filters";
import "pixi-particles";
import "pixi-spine";

window.PIXI["default"] = PIXI;

export default window.PIXI;`

Then... import PIXI from vendor/pixi; 

Now I've updated dependencies to newest version, to 5.3.3, also all plugins. I've changed pixi.js import as reccommended to: 
`import * as PIXI from "pixi.js"` ... And now it seems, that global/window PIXI is not exposed to the plugins. I tried window.PIXI = PIXI, or global.PIXI = PIXI, but it seems doesn't work.

As I've read in this thread above here, should I use any other build instead of npm versions? Or am I missing something else, how to expose the global PIXI to the plugins, or how to better import the plugins? Are the listed plugins compatible with newest pixi release? ... PIXI.animate git hub page says dependency for pixi v4, but in commits I've seen v5 support, so I'm not sure.

Thanks in advance for any help, best regards, M.
