### ISSUE TITLE
Different result for flip using mat4 library 

### ISSUE THREAD

**Issue by a-c-sreedhar-reddy** [pixijs/pixi-projection#90]
Hi,

I was using mat4 from `gl-matrix` library to generate a flip by applying following steps.

- translate to the origin
- rotate x,y,z
- multiply with a lookAt matrix ( eye position is at 0,0,1)
- multiply with a perspective matrix (FOV: 90 deg)
- translate back to the original Position 

The image flips. But it is not similar to what  pixi-projection generates. What can be the cause of this?

**Comment by ivanpopelyshev** [comment]
need more details :)

**Comment by a-c-sreedhar-reddy** [comment]
Hi @ivanpopelyshev ,

This fiddle uses gl-matrix library: https://jsfiddle.net/acsreedharreddy/2u9jnpgc/6/

This fiddle uses pixi-projection : https://jsfiddle.net/acsreedharreddy/7yaqp51L/8/

**Comment by ivanpopelyshev** [comment]
so, you dont know which `perspective` value to use there, right?

**Comment by a-c-sreedhar-reddy** [comment]
I am not sure what `the lookAt and perspective's field of view` in gl-matrix should be?

**Comment by ivanpopelyshev** [comment]
pixi-projection needs distance from the display to your eyes, in units (usually pixels). That's different from FOV because projection doesnt know about width/height of your monitor :)

Suppose you have horizontal FOV 90, half of it is 45, that means distance to monitor is equal to half of this monitor.

If i pass 350/2 instead of your 2000, it looks the same as gl-matrix.

In general `width/2 * cotan(fov/2)` if its horizontal fov.

**Comment by ivanpopelyshev** [comment]
Why i used that param instead of FOV: in 2d space its important that changes in width/height do not affect the resulting image per pixel. Imagine that after changing width/height your parrot rotates differently - that's what i want to evade.

In 3d its all about aspect ratio and sometimes FOV of minimal dimension. Its good for responsiveness but its different, maybe i'll add this mode later. There are also things like "noots" , which is "1/100 of minimal dimensions" , units that are very handy there.

**Comment by a-c-sreedhar-reddy** [comment]
I wanted to generate the pixi-projection flip effect using gl-matrix.

But in the above [gl-matrix fiddle](https://jsfiddle.net/acsreedharreddy/2u9jnpgc/7/) the image appears to come close to the camera. Whereas in the [pixi-projection fiddle](https://jsfiddle.net/acsreedharreddy/7yaqp51L/8/) it does not.

When I try to position the camera farther from the image, then the image size gets reduced.

**Comment by ivanpopelyshev** [comment]
> When I try to position the camera farther from the image, then the image size gets reduced.

now you know why i chose this param instead of FOV :) Well, you have the equation - obviously, you have to adjust both width and FOV to match effect from projection.

**Comment by a-c-sreedhar-reddy** [comment]
Thanks @ivanpopelyshev I have managed to get the correct camera position and the FOV to look similar to pixi-projection.

I have one doubt. If some part of the image is out of the canvas then does not pixijs paint it?
eg: [fiddle](https://jsfiddle.net/acsreedharreddy/2u9jnpgc/42/)

**Comment by a-c-sreedhar-reddy** [comment]
setting autofit to false fixed this issue. Thanks
